Update mac.yml

diff --git a/.github/workflows/mac.yml b/.github/workflows/mac.yml
--- a/.github/workflows/mac.yml
+++ b/.github/workflows/mac.yml
@@ -25,24 +25,30 @@ jobs:
       - name: Installing main libraries
         run: |
           export DYLD_LIBRARY_PATH=/Users/runner/hostedtoolcache/neko/2.3.0/x64:/usr/local/lib
-              haxelib install lime
-              haxelib install openfl
-              haxelib install flixel
-              haxelib install flixel-tools
-              haxelib install flixel-addons
-              haxelib install hxcpp-debug-server
-              haxelib install hxvlc
-              haxelib install hscript
-              haxelib install flixel-text-input
-      - name: Setting up HaxeFlixel
-        run: |
-          export DYLD_LIBRARY_PATH=/Users/runner/hostedtoolcache/neko/2.3.0/x64:/usr/local/lib
-              haxelib run lime setup
-              haxelib run lime setup flixel
-              haxelib run flixel-tools setup  
+          haxelib install lime
+          haxelib install openfl
+          haxelib install flixel
+          haxelib install flixel-tools
+          haxelib install flixel-addons
+          haxelib install hxcpp-debug-server
+          haxelib install hxvlc
+          haxelib install hscript
+          haxelib install flixel-text-input
+
       - name: Verifying Libraries
         run: |
           haxelib list
+
+      - name: Setting up HaxeFlixel
+        run: |
+          export DYLD_LIBRARY_PATH=/Users/runner/hostedtoolcache/neko/2.3.0/x64:/usr/local/lib
+          haxelib run lime setup
+          haxelib run lime setup flixel
+
+      - name: Setting up Flixel Tools
+        run: |
+          export DYLD_LIBRARY_PATH=/Users/runner/hostedtoolcache/neko/2.3.0/x64:/usr/local/lib
+          haxelib run flixel-tools setup || echo "Flixel Tools setup failed"
 
       - name: Building the game
         run: |
